steps:
  # Step 1: Use the base image to build the JAR file
  - name: 'eclipse-temurin:21-jdk-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - 'apk add --no-cache maven && mvn clean package'

  # Step 2: Build the Docker image using the built JAR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/apibills/bills-rest-server-gcp:latest',
        '.',
      ]

images:
  - 'gcr.io/apibills/bills-rest-server-gcp:latest'